USE master
CREATE DATABASE SpNova
GO

USE SpNova
CREATE TABLE Requests(
	R_Id		BIGINT			IDENTITY(1, 1),
	R_Email		VARCHAR(128)	NOT NULL,
	R_Status	VARCHAR(16)		NOT NULL,
	R_Caption	NVARCHAR(512)	NOT NULL,
	R_URL		NVARCHAR(4000)	NULL,
    R_FileName  NVARCHAR(900)   NULL,
	R_CreatedAt	DATETIME2		NOT NULL,
	R_UpdatedAt	DATETIME2		NOT NULL,

	CONSTRAINT PKRequests PRIMARY KEY(R_Id)
)
