<?php

namespace App\Services\Requests\ImageGenerating\Pipes;

use App\Contracts\ObjectStorage;
use App\Data\PipelinePayload;
use App\Exceptions\ObjectStorageException;
use Closure;
use Illuminate\Support\Facades\Storage;

/**
 * Pipeline step: write the generated bytes to local disk briefly, then
 * upload to the output bucket via the {@see ObjectStorage} port.
 *
 * The two-step (local→remote) flow exists because the underlying SDK
 * accepts a SourceFile path; if a future adapter supports streams we
 * can collapse this to a single call without changing pipe wiring.
 */
final readonly class UploadGeneratedImage
{
    public function __construct(
        private ObjectStorage $storage,
    ) {}

    /**
     * @throws ObjectStorageException
     */
    public function handle(PipelinePayload $payload, Closure $next): mixed
    {
        $bucket   = (string) config('image_generator.storage.output_bucket');
        $fileName = $payload->history->file_name;

        Storage::put($fileName, $payload->imageBytes ?? '');

        try {
            $payload->generatedUrl     = $this->storage->put(
                localPath: Storage::path($fileName),
                bucket:    $bucket,
                key:       $fileName,
            );
            $payload->history->url     = $payload->generatedUrl;
        } finally {
            Storage::delete($fileName);
            $payload->imageBytes = null;
        }

        return $next($payload);
    }
}
